### ISSUE TITLE
selectById Parameters: null

### ISSUE THREAD

**Issue by JunlinHe** [fangjinuo/sqlhelper#132]
您好，我使用的是sqlhelper-mybatisplus-spring-boot-starter:3.0.1
当我调用selectById时控制台输出的sql参数为空，如图所示：
![image](https://user-images.githubusercontent.com/10608354/82044266-9df25800-96df-11ea-8a3f-a7015a255ecc.png)

我的id是Long类型，且名称为id，我使用构造查询时一切都正常
`
roleService.getOne(Wrappers.<Role>lambdaQuery().eq(Role::getId, roleId));
`
尝试了很多办法，最后升级依赖mybatis-plus:3.3.0，并且解决com.baomidou.mybatisplus.autoconfigure.ConfigurationCustomizer接口的升级兼容性问题，再次调用selectById，参数为空的问题就没有了，这个或许是mybatisplus:3.2.0的问题，所以我想问您是否会考虑升级mybatisplus依赖

**Comment by fangjinuo** [comment]
这个依赖关系应该不是强制性捆绑的，你可以把 sqlhelper-mybatisplus-spring-boot-starter 依赖的 mybatis-plus 排除后，自己直接引入高版本的。

我这边做个验证即可

**Comment by JunlinHe** [comment]
我的做法不够严谨，刚又试了一遍，升级mybatisplus并没有解决问题

**Comment by fangjinuo** [comment]
那问题原因呢------------------ Original ------------------From: JunlinHe  <notifications@github.com>Date: Fri,May 15,2020 8:13 PMTo: fangjinuo/sqlhelper <sqlhelper@noreply.github.com>Cc: fangjinuo <fs1194361820@163.com>, Comment <comment@noreply.github.com>Subject: Re: [fangjinuo/sqlhelper] selectById Parameters: null (#132)
我的做法不够严谨，刚又试了一遍，升级mybatisplus并没有解决问题

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/fangjinuo/sqlhelper/issues/132#issuecomment-629200896",
"url": "https://github.com/fangjinuo/sqlhelper/issues/132#issuecomment-629200896",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by JunlinHe** [comment]
@fangjinuo 问题原因还没找到，这是我的[demo](https://github.com/JunlinHe/sqlhelper-demo)

**Comment by fangjinuo** [comment]
我看了你的demo，我的外网机器上没有安装mysql, 并且也没有表
能否帮忙搞一个 基于 h2数据库的，只需要把你的数据库的 换成 h2的即可。
这样我拉下来就可以运行的

**Comment by fangjinuo** [comment]
另外在你调整数据库之前，先在 application.yaml加入下面的配置：

sqlhelper:
  mybatis:
    instrumentor:
      name: mybatis
      cache-instrumented-sql: true
      subquery-paging-start-flag: "[PAGING_START]"
      subquery-paging-end-flag: "[PAGING_END]"

**Comment by JunlinHe** [comment]
@fangjinuo [h2demo](https://github.com/JunlinHe/sqlhelper-demo-h2)

**Comment by fangjinuo** [comment]
造了7条数据，查询是page参数：pageSize 5, pageNo 1，结果如下：

```json
{"pageNo":1,"pageSize":5,"total":7,"items":[
{"id":1,"name":"zhangsan"},
{"id":2,"name":"zhangsan002"},
{"id":3,"name":"zhangsan003"},
{"id":4,"name":"zhangsan004"},
{"id":5,"name":"zhangsan005"}
],
"maxPageCount":2,
"maxPage":2}
```

第二次测试，只传 pageSize= 10，（你的程序默认 pageNo=1）结果如下:
```json
{"pageNo":1,"pageSize":10,"total":7,"items":[
{"id":1,"name":"zhangsan"},
{"id":2,"name":"zhangsan002"},
{"id":3,"name":"zhangsan003"},
{"id":4,"name":"zhangsan004"},
{"id":5,"name":"zhangsan005"},
{"id":6,"name":"zhangsan006"},
{"id":7,"name":"zhangsan007"}
],"maxPageCount":1,"maxPage":1}
```

**Comment by fangjinuo** [comment]
![h2demo_snapshot](https://user-images.githubusercontent.com/8428331/82329675-453efa00-9a14-11ea-8f67-d69a92800248.png)

**Comment by JunlinHe** [comment]
分页条件查询并没有问题，但是selectById便...
![image](https://user-images.githubusercontent.com/10608354/82393186-499cfe80-9a78-11ea-816f-8a0ca44e4819.png)

**Comment by fangjinuo** [comment]
用3.0.3 版本测试一下

**Comment by JunlinHe** [comment]
ok了，但是在我的[h2demo](https://github.com/JunlinHe/sqlhelper-demo-h2)基础上出现 #131 的问题，我增加了sqlhelper-jsqlparser和spring-boot-starter-validation两个依赖
